# Generated by Django 4.2.1 on 2023-10-03 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='assignmentinstructions',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='examdetails',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='assessment',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='correct_option',
            field=models.CharField(choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3'), ('4', 'Option 4')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option1',
            field=models.CharField(default='Option 1', max_length=200),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option2',
            field=models.CharField(default='Option 2', max_length=200),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option3',
            field=models.CharField(default='Option 3', max_length=200),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option4',
            field=models.CharField(default='Option 4', max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_text',
            field=models.TextField(default='Enter your question here'),
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='AssignmentInstructions',
        ),
        migrations.DeleteModel(
            name='ExamDetails',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.quiz'),
        ),
    ]
